# https://dvcs.w3.org/hg/gld/raw-file/default/data-cube/index.html#ic-3

ASK {
  ?dsd a qb:DataStructureDefinition .
  FILTER NOT EXISTS { ?dsd qb:component [qb:componentProperty [a qb:MeasureProperty]] }
}